# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0f4c8989fd93b92da725d2fc939cf4be61ff0b0de26ac296629d5c2b473c0348dbdf85708b13cd7db832afdf0f33f24959a56dd1487079bb57559fc4ec847ed

test:
  secret_key_base: bf02f158d35977281b90d189202c939c1b04fe9d7d790ce9b4f5fd55726c1c5bb4d889c66e4961e9a2a4c063b60db07d23be29975b75eddd26a4489131db0c82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
